# Generated by Django 2.2.4 on 2019-09-08 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuesto',
            name='iva',
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='price',
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='iva_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='cuit',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='client',
            name='sale_condition',
            field=models.CharField(choices=[('CTD', 'Contado'), ('CCT', 'Cuenta Corriente')], default='CTD', max_length=3),
        ),
        migrations.AlterField(
            model_name='company',
            name='iva_condition',
            field=models.CharField(choices=[('CTD', 'contado'), ('RIN', 'Responsable Inscripto')], default='CTD', max_length=3),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Presupuesto')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Product')),
            ],
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='productos',
            field=models.ManyToManyField(related_name='product', through='base.Products', to='base.Product'),
        ),
    ]
