# Generated by Django 2.2.4 on 2019-09-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20190908_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='final_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='iva',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='products',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='products',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
