# Generated by Django 2.2.4 on 2019-09-10 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20190910_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presupuesto',
            old_name='productos',
            new_name='products_list',
        ),
    ]
