# Generated by Django 2.2.4 on 2019-09-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20190910_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuesto',
            name='product_total_price',
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
