# Generated by Django 2.2.4 on 2019-09-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20190910_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presupuesto',
            old_name='presupuesto_total_price',
            new_name='total_after_discounts',
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='total_before_discounts',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
