# Generated by Django 2.2.4 on 2019-09-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20190915_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='total_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
