# Generated by Django 2.2.4 on 2019-09-21 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_presupuesto_total_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Client'),
        ),
    ]
