# Generated by Django 2.2.4 on 2019-09-21 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_presupuesto_client'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Item',
        ),
    ]
