# Generated by Django 2.2.4 on 2019-09-21 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20190921_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presupuesto',
            old_name='products_list',
            new_name='items',
        ),
    ]
