# Generated by Django 2.2.4 on 2019-09-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20190921_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='items',
            field=models.ManyToManyField(related_name='presupuesto_producto', through='base.Item', to='base.Product'),
        ),
    ]
