# Generated by Django 2.2.4 on 2019-09-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20190921_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='items',
            field=models.ManyToManyField(through='base.Item', to='base.Product'),
        ),
    ]
