# Generated by Django 2.2.4 on 2019-10-05 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20190921_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Company'),
        ),
    ]
