# Generated by Django 2.2.4 on 2019-11-06 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20191106_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cuit',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='company',
            name='iibb',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
