# Generated by Django 2.2.4 on 2019-11-16 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20191116_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Company'),
        ),
    ]
