# Generated by Django 2.2.4 on 2019-11-16 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_auto_20191116_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='base.Company'),
            preserve_default=False,
        ),
    ]
