# Generated by Django 2.2.4 on 2019-11-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_client_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='iva_condition',
            field=models.CharField(choices=[('INS', 'Inscripto'), ('EXC', 'Exento'), ('CFI', 'Consumidor Final')], default='CFI', max_length=3),
        ),
    ]
