# Generated by Django 2.2.4 on 2019-11-24 01:30

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_auto_20191123_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name_bussinessname']},
        ),
        migrations.AlterModelOptions(
            name='presupuesto',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='client',
            name='cuit',
            field=models.CharField(max_length=11, validators=[utils.validators.cuit_validator]),
        ),
    ]
