# Generated by Django 2.2.4 on 2020-02-09 23:37

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_auto_20191123_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='picture',
        ),
        migrations.AlterField(
            model_name='company',
            name='cuit',
            field=models.CharField(max_length=11, validators=[utils.validators.cuit_validator]),
        ),
    ]
